// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6fstxIfM3mNtyk6aQL_IPC0uWapP-Zc',
    appId: '1:41952984866:web:79547e692447015f0baf7b',
    messagingSenderId: '41952984866',
    projectId: 'btm-mobile',
    authDomain: 'btm-mobile.firebaseapp.com',
    storageBucket: 'btm-mobile.firebasestorage.app',
    measurementId: 'G-0B6CEWT9EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEzsjRx_NqAx2p7JkyCO8PtC_QWvmzdA',
    appId: '1:41952984866:android:b63fc535f7f03fe80baf7b',
    messagingSenderId: '41952984866',
    projectId: 'btm-mobile',
    storageBucket: 'btm-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX7Yp7dfCJDxXtGOSls6_x4ZAxD_XdoCQ',
    appId: '1:41952984866:ios:07c00cf8bc4193f60baf7b',
    messagingSenderId: '41952984866',
    projectId: 'btm-mobile',
    storageBucket: 'btm-mobile.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX7Yp7dfCJDxXtGOSls6_x4ZAxD_XdoCQ',
    appId: '1:41952984866:ios:07c00cf8bc4193f60baf7b',
    messagingSenderId: '41952984866',
    projectId: 'btm-mobile',
    storageBucket: 'btm-mobile.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_6fstxIfM3mNtyk6aQL_IPC0uWapP-Zc',
    appId: '1:41952984866:web:a6022824d7c19ac40baf7b',
    messagingSenderId: '41952984866',
    projectId: 'btm-mobile',
    authDomain: 'btm-mobile.firebaseapp.com',
    storageBucket: 'btm-mobile.firebasestorage.app',
    measurementId: 'G-QWHFZ88EG5',
  );
}